import Head from 'next/head'
import dynamic from 'next/dynamic'
import IpInfo from '@/src/components/IpInfo';
import { useEffect, useState } from 'react';
import getInfo, { IpLocation } from '@/src/utils/ip.utils';

const LocationMap = dynamic(() => import('@/src/components/LocationMap'), {ssr: false});


export default function Home() {
  const [ipInput, setIpInput] = useState<string>("");
  const [ipLocation, setIpLocation] = useState<IpLocation>();
  const [searchError, setSearchError] = useState<string>("");

  const fetchIpInfo = () => {
    getInfo(ipInput)
      .then(data => setIpLocation(data))
      .catch(error => {
        setSearchError(error.message);
        setTimeout(() => {
          setSearchError("");
        }, 2000);
      });
  }

  useEffect(() => {
    fetchIpInfo();
  }, []);
  return (
    <>
      <Head>
        <title>IP Address Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </Head>
      <main>
        <div className="search-form">
          <h1>IP Address Tracker</h1>
          <div className='search-input'>
            <input
              type="search"
              onChange={(e) => setIpInput(e.target.value)}
              value={ipInput}
              placeholder="Search for any IP address"
              />
            <button onClick={fetchIpInfo}>Search</button>
          </div>
          {searchError ? <p className='error'>{searchError}</p> : <></>}
          {ipLocation ? <IpInfo info={ipLocation} /> : <></>}
        </div>
        {ipLocation ? (
          <>
            <LocationMap lat={ipLocation.location.lat} lon={ipLocation.location.lng} zoom={13} />
          </>
        ) : <p>Loading...</p>}
      </main>
    </>
  )
}
